apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: c2E=
  postgres-password: UGFzc3dvcmQxIQ==
  postgres-url: amRiYzpwb3N0Z3Jlc3FsOi8vZGI6NTQzMi9wcmllbXRlc3Rlcg==