apiVersion: apps/v1
kind: Deployment
metadata:
  name: priemtester-deployment
  labels:
    app: priemtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priemtester
  template:
    metadata:
      labels:
        app: priemtester
    spec:
      containers:
      - name: priemtester
        image: ghcr.io/joostvophuizen/priemtester:latest
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: 'none'
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: priemtester-service
spec:
  type: NodePort
  selector:
    app: priemtester
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000